title: WMC-3xHIF
description: WMC Learning Hub
theme: just-the-docs
# remote_theme: just-the-docs/just-the-docs

url: https://michel-spg.github.io/wmc-3xhif

collections:
  docs:
    output: true
    permalink: /:collection/:path/